spring.application.name=flotrack
spring.datasource.url=jdbc:h2:file:./data/flotrackdb
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.datasource.driverClassName=org.h2.Driver

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

security.jwt.expiration-time=3600000
springdoc.show-actuator: true
springdoc.api-docs.path: /v3/api-docs
springdoc.swagger-ui.enabled: true
springdoc.swagger-ui.url: /v3/api-docs